/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvcsingleton;

/**
 *
 * @author Breakermoob
 */
public class InterfazResultados extends javax.swing.JFrame implements InterfazVista {

    /**
     * Creates new form InterfazResultados
     */
    public InterfazResultados() {
        super("Los resultados son: ");
        initComponents();
        botonSalir.setActionCommand(salir);
        botonVolver.setActionCommand("volver");
        ejSingleton.setActionCommand("singleton");
    }
    public void mostrarResultado(String res){
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        textResultado.setText(res);
    }
    @Override
    public void setControlador(ControlIMC c){
        botonSalir.addActionListener(c);
        botonVolver.addActionListener(c);
        ejSingleton.addActionListener(c);
    }
    @Override
    public void cerrarAplicacion(){
        System.exit(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textResultado = new javax.swing.JTextArea();
        botonVolver = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        ejSingleton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 320));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textResultado.setBackground(new java.awt.Color(215, 215, 215));
        textResultado.setColumns(20);
        textResultado.setRows(5);
        textResultado.setPreferredSize(new java.awt.Dimension(166, 94));
        jScrollPane1.setViewportView(textResultado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 44, 270, -1));

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(botonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 190, 100, 30));

        botonSalir.setText("Salir");
        getContentPane().add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 190, 120, 30));

        ejSingleton.setText("¿Qué significa esto?");
        getContentPane().add(ejSingleton, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 250, 270, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1338667064_965410_1338667236_noticia_normal.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazResultados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonVolver;
    private javax.swing.JButton ejSingleton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textResultado;
    // End of variables declaration//GEN-END:variables
}
